---
- name: Change to ssh remote
  command: git remote set-url origin "{{ bootstrap_url }}"

- name: Check notes exists
  stat:
    path: "{{ notes_directory }}"
  register: notes_directory
- name: Git clone notes
  command: git clone "{{ notes_url }}" "{{ notes_directory }}"
  when: not notes_directory.stat.exists

- name: Check zettelkasten exists
  stat:
    path: "{{ zettel_directory }}"
  register: notes_directory
- name: Git clone work-notes
  command: git clone "{{ zettel_url }}" "{{ zettel_directory }}"
  when: not notes_directory.stat.exists

- name: Check work-notes exists
  stat:
    path: "{{ work_notes_directory }}"
  register: notes_directory
- name: Git clone work-notes
  command: git clone "{{ work_notes_url }}" "{{ work_notes_directory }}"
  when: not notes_directory.stat.exists

- name: Check online-resume exists
  stat:
    path: "{{ online_resume_directory }}"
  register: notes_directory
- name: Git clone online-resume
  command: git clone "{{ online_resume_url }}" "{{ online_resume_directory }}"
  when: not notes_directory.stat.exists

- name: Check nvim-agenda exists
  stat:
    path: "{{ nvim_agenda_directory }}"
  register: notes_directory
- name: Git clone nvim-agenda
  command: git clone "{{ nvim_agenda_url }}" "{{ nvim_agenda_directory }}"
  when: not notes_directory.stat.exists
